SEVENN: Scalable EquVariance-Enabled Neural Network
sevenn version 0.9.2
reading yaml config...
                ****
              ********                                   .
              *//////,  ..                               .            ,*.
               ,,***.         ..                        ,          ********.                                  ./,
             .      .                ..   /////.       .,       . */////////                               /////////.
        .&@&/        .                  .(((((((..     /           *//////*.  ...                         *((((((((((.
     @@@@@@@@@@*    @@@@@@@@@@  @@@@@    *((@@@@@     (     %@@@@@@@@@@  .@@@@@@     ..@@@@.   @@@@@@*    .(@@@@@(((*
    @@@@@.          @@@@         @@@@@ .   @@@@@      #     %@@@@         @@@@@@@@     @@@@(,  @@@@@@@@.    @@@@@(*.
    %@@@@@@@&       @@@@@@@@@@    @@@@@   @@@@@      #  ., .%@@@@@@@@@    @@@@@@@@@@   @@@@,   @@@@@@@@@@   @@@@@
    ,(%@@@@@@@@@    @@@@@@@@@@     @@@@@ @@@@&       (//////%@@@@@@@@@    @@@@  @@@@@@ @@@@  . @@@@@  @@@@@.@@@@@
        .   @@@@@   @@@@ .       .  @@@@@@@@%   . . ( .////,%@@@@         @@@@    @@@@@@@@@    @@@@@    @@@@@@@@@
    (@@@@@@@@@@@    @@@@@@@@@@**.    @@@@@@*       *.      .%@@@@@@@@@@   @@@@    . @@@@@@@    @@@@@     .@@@@@@@
     @@@@@@@@@.     @@@@@@@@@@///,    @@@@.      . /        %@@@@@@@@@@   @@@@***,    @@@@@    @@@@@        @@@@@
           .           //////////*.               /           .            .*******...             . ,.
          .&&&&&...     ,//////*.       ...////.  /            ,*/.     .   ,////,               .,/////
          &@@@@@@                         ,(/((, *           ,((((((.                              .***.
           ,/@(,                            ..   *            ,((((*
                                                ,
                                               .
Unknown error occured!
Traceback (most recent call last):
  File "/home/parkyutack/.local/lib/python3.8/site-packages/sevenn/main/sevenn.py", line 63, in main
    model_config, train_config, data_config = read_config_yaml(input_yaml)
  File "/home/parkyutack/.local/lib/python3.8/site-packages/sevenn/parse_input.py", line 276, in read_config_yaml
    with open(filename, 'r') as fstream:
IsADirectoryError: [Errno 21] Is a directory: 'continue_test/'
